### ISSUE TITLE
Ensure releases on PyPI contain a wheel

### ISSUE THREAD

**Issue by Ruturaj4** [abseil/abseil-py#105]
I observed that the package is using `sdist`. My question is why not use `wheel`? Considering all the advantages provided by `wheel`.

**Comment by gpshead** [comment]
What advantages does a wheel provide over sdist when there are no precompiled binary extension modules?

(anyways I think a future version of twine or pip or whatnot is supposed to auto-wheel-ify packages all the time anyways?)

**Comment by rickeylev** [comment]
I think (not entirely sure of this) that in our case, the main advantage of a wheel is it decouples the building from the installing to certain extent. I think it would have prevented the bug a couple months ago where I used a feature in setup.py that required a newer version of setuptools, but, it turns out, some people using absl end up with a _very_ old setuptools version from their distro. I think wheels would have prevented that.

**Comment by gpshead** [comment]
That makes sense.  Easy enough to package up as a wheel for future uploads.

**Comment by rickeylev** [comment]
No particular reason. Just lack of time to figure it out.

**Comment by groodt** [comment]
I see that a new release of abseil-py has gone out without a wheel. Probably an oversight more than anything else. Would it be a good idea to setup a repeatable PyPI release process or playbook document? It can either be a README, or a Makefile, or a script or perhaps Bazel can do it (might be more complex).

**Comment by phalecs** [comment]
Is there any chance this issue will be re-opened or addressed anytime soon?

**Comment by yilei** [comment]
Hi, we just pushed out a new release 0.10.0 including a wheel for Python 3. Let us know if you see any issues.

Closing.
