### ISSUE TITLE
//absl/flags:tests/_validators_test failing on macOS on Bazel CI with Bazel 

### ISSUE THREAD

**Issue by laszlocsomor** [abseil/abseil-py#108]
At https://github.com/abseil/abseil-py/commit/9d73fdaa23a6b6726aa5731390f388c0c6250ee5 with Bazel 0.28.0 `//absl/flags:tests/_validators_test` is failing.

https://buildkite.com/bazel/abseil-python/builds/832#0170d5cb-302b-4c10-ad05-05cdb7af6b0d
```
======================================================================
FAIL: test_flag_default_not_none_warning (__main__.MarkFlagAsRequiredTest)
test_flag_default_not_none_warning (__main__.MarkFlagAsRequiredTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_buildkite/e40ec35ca2e2e5ea6d861f329e114d88/sandbox/darwin-sandbox/77/execroot/io_abseil_py/bazel-out/darwin-fastbuild/bin/absl/flags/tests/_validators_test.runfiles/io_abseil_py/absl/flags/tests/_validators_test.py", line 626, in test_flag_default_not_none_warning
    self.assertLen(w, 1)
  File "/private/var/tmp/_bazel_buildkite/e40ec35ca2e2e5ea6d861f329e114d88/sandbox/darwin-sandbox/77/execroot/io_abseil_py/bazel-out/darwin-fastbuild/bin/absl/flags/tests/_validators_test.runfiles/io_abseil_py/absl/testing/absltest.py", line 785, in assertLen
    container_repr, len(container), expected_len), msg)
  File "/private/var/tmp/_bazel_buildkite/e40ec35ca2e2e5ea6d861f329e114d88/sandbox/darwin-sandbox/77/execroot/io_abseil_py/bazel-out/darwin-fastbuild/bin/absl/flags/tests/_validators_test.runfiles/io_abseil_py/absl/testing/absltest.py", line 1611, in fail
    return super(TestCase, self).fail(self._formatMessage(prefix, msg))
AssertionError: [<warnings.WarningMessage object at 0x10d045588>, <warnings.WarningMessage object at 0x10d0455f8>] has length of 2, expected 1.
```

**Comment by rickeylev** [comment]
Thanks for the report. I had seen this failure internally but didn't think it was in the recent OSS release since it's been awhile since such a release.

This seems to be specific to OSS and non-google Macs in some way. The test passes on my corporate laptop with 0.28; I can't repro it directly. I _can_ repro it via kokoro, though (this makes debugging it much harder though).

**Comment by rickeylev** [comment]
Aha, I think two things were going on:
1. The tests are capturing warnings and performing asserts while capturing is on.
2. assertLen triggers a warning (it accesses collections.Sized instead of collections.abc.Sized)

If assertLen is moved out of the warning capturing, or collections.abc.Sized is accessed instead, then the error goes away.

**Comment by rickeylev** [comment]
Actually, the above is just half the story. The bazelbuild link in the OP is running tests using Python 3.7, which isn't technically supported by absl. However, our internal builds are _also_ using Python 3.7 despite us setting everything up to use different Python versions entirely. At first glance, it looks like bazel is always using /usr/local/bin/python3 instead of what is being specified by --python_path

This looks like either a bazel bug, or we have to change how we're telling bazel what python to use.

**Comment by gpshead** [comment]
Side note: absl needs to support 3.7 today (and 3.8 later this year). That is what users of external projects expect.  So if we're running tests on 3.7 even unplanned, that was a good thing in a way...
