### ISSUE TITLE
Flag usage

### ISSUE THREAD

**Issue by ewhauser** [abseil/abseil-py#13]
I've been experimenting with the flags module and had a question. From the documentation:

> """This package is used to define and parse command line flags.
This package defines a *distributed* flag-definition policy: rather than
an application having to define all flags in or near main(), each Python
module defines flags that are useful to it.  When one Python module
imports another, it gains access to the other's flags.  (This is
implemented by having all modules share a common, global registry object
containing all the flag information.)
Flags are defined through the use of one of the DEFINE_xxx functions.
The specific function used determines how the flag is parsed, checked,
and optionally type-converted, when it's seen on the command line.
"""

If flags are defined in different packages `__init__.py` files, how are they discovered prior to parsing the flags? For instance, assume a standard project:

`module/__init__.py`

```python
if __name__ == "__main__":
  FLAGS(argv)
  server.start()
```

And our server object uses a library called foo that defines a flag that is not imported until the server is actually invoked:

`module/foo/__init__.py`
```python
DEFINE_string('debug', None, 'Debug mode')
```

This will raise an error as the flag definition will not be known by flags yet. I'm probably missing something here - looking for guidance.

**Comment by gpshead** [comment]
Our flags library assumes that your application does all imports at application startup time before `app.run(main)` is called rather than delayed dynamic imports at runtime.

In situations where there are potential delayed imports (some web frameworks seem to be a fan of this) we have suggested that people either:
   1. manually do all of the potential imports their server may do up front (ugh?) _or_
   2. at least create a single module of flag definitions that you expect all of those to need and always import that regardless of which subset of modules your server ends up actually importing later on.

**Comment by ewhauser** [comment]
Thanks - makes sense. Option 2 is a reasonable approach when dealing with a larger package that provides a number of modules that are exposing flags. Appreciate the response.
