### ISSUE TITLE
Running all tests without requiring bazel? (test discovery)

### ISSUE THREAD

**Issue by ataiya** [abseil/abseil-py#138]
The introduction [here](https://abseil.io/docs/python/guides/testing) creates an analogy between abseil-py and python native "unittest". From the [readme](https://github.com/abseil/abseil-py) it seems that to run tests bazel is required.

Does abseil provide a "test discovery" alike unittest? ([see docs](https://docs.python.org/3/library/unittest.html#command-line-interface))
```
# When executed without arguments Test Discovery is started:
python -m unittest
```

**Comment by yilei** [comment]
abseil doesn't have special logic for test discovery. Since `absl.testing.absltest` is built on top of `unittest`, if you just use `absl.testing.absltest.TestCase` over `unittest.TestCase` in your code, `python -m unittest` would also work.

But if your test or your test dependencies also define flags with `absl.flags`, `python -m unittest` will likely fail because `absltest.main()` is not called (it parses flags and does some extra things).

We usually define a test module with the following main block:

```
from absl.testing import absltest
if __name__ == '__main__':
  absltest.main()  # Parses flags and does some extra things
```

and execute the modules separately as main programs, and it doesn't require bazel.

Does this answer your question?

**Comment by ataiya** [comment]
I think so, as far as I add the main block above, then I can recycle the unittest logic.
Let me test it (aha!) and I will close it if it works well.

**Comment by ataiya** [comment]
Worked like a charm:
https://github.com/tensorflow/graphics/pull/296

Closing the issue.

**Comment by juneoh** [comment]
Re https://github.com/abseil/abseil-py/issues/138#issuecomment-623699242: as @yilei said -- 

> But if your test or your test dependencies also define flags with `absl.flags`, `python -m unittest` will likely fail because `absltest.main()` is not called (it parses flags and does some extra things).

While `python -m unittest` and `pytest` may seem to work, they may have unexpected side affects as the `absltest.main()` is not called to parse the flags etc.

Instead, a better workaround would be to [trigger the test discovery within the `unittest.TestProgram`](https://github.com/python/cpython/blob/d6259c58cbb48b8f3fbd70047f004ea19fe91e86/Lib/unittest/main.py#L125) that `absltest.main()` uses, simply by:

```python
absltest.main(module=None)
```

And then call the above line e.g. via entry point script, or a `__main__.py` within the test directory.

**Comment by LukeGT** [comment]
For anyone who stumbles across this and wants to also pass flags to the unittest discovery command, e.g. to provide a pattern, you can do it like this:

```
import sys

from absl.testing import absltest

if __name__ == '__main__':
  discovery_args = ['discover', '-p', '*_test.py']
  absltest.main(
      module=None,
      argv=[sys.argv[0], *discovery_args],
  )
```
