### ISSUE TITLE
How to test several files in Github Workflow?

### ISSUE THREAD

**Issue by charbull** [abseil/abseil-py#140]
Is it possible to run several tests with abseil? in a github workflow where if one test fails the overall action fails?

Thank you

**Comment by yilei** [comment]
By "run several tests", I assume you mean serval test files.

1. Do you need abseil for your tests? Does plain `unittest` work for you? It supports [Test Discovery](https://docs.python.org/3/library/unittest.html#test-discovery) which runs tests with a single command, I assume this is possible in github workflow. (Or https://docs.pytest.org/en/latest/?)

2. If you do need abseil because the libraries you are testing are using abseil (e.g. for `absl.flags`), similar reasons behind https://github.com/abseil/abseil-py/issues/138#issuecomment-623689565, you might need a higher level script to run each individual test module as main programs.

**Comment by charbull** [comment]
Thank you that worked ! by relying on unittest discovery
