### ISSUE TITLE
When did you provide absl::Duration / and absl::Time Cliff wrapper ? 

### ISSUE THREAD

**Issue by Mizux** [abseil/abseil-py#145]
All in the title, currently it make difficult for google projects to provide python (SWIG) wrappers based on abseil-cpp types...

Since both project abseil-cpp and abseil-py are part of the federation you should sync types between them... (ed also wait to see Java and C# wrapper in cliff (half joking))

**Comment by gpshead** [comment]
We recommend Open Source projects use [pybind11](https://github.com/pybind/pybind11) for Python <-> C++ interoperability. Not CLIF and not SWIG.

While we have **internal** absl C++<->Python integration _(currently CLIF based)_, that has not been released as part of the open source abseil-py as the open source C++ absl does not yet contain everything that integration requires in order to make sense and we cannot release it so long as it is built upon CLIF. I expect we'll have it using pybind11 before absl C++/Python integration can be released as open source.

No ETA.
