### ISSUE TITLE
Importing TensorFlow causes argparse_flags.ArgumentParser to fail when specifying an argument_default

### ISSUE THREAD

**Issue by kentslaney** [abseil/abseil-py#171]
Basically just the title. This code fails:

```python
import tensorflow as tf
from absl.flags.argparse_flags import ArgumentParser

ArgumentParser(argument_default=42)
```

[Here it is in Colab](https://colab.research.google.com/drive/1rNMHU4XrzE3t8Qs7DLwOZ_OcUHcDPgv6?usp=sharing).

Edit: I should clarify, it [*only* fails if tensorflow is imported](https://colab.research.google.com/drive/1Jg6PXvx9Q3oGhkJ_EKSkRod_JgsNWDwM?usp=sharing)

**Comment by yilei** [comment]
Thanks for filing the bug. Looks like `argument_default=` simply doesn't work if you have any `absl.flags` flag defined. This is because [a `default=` argument is passed to custom actions](https://github.com/python/cpython/blob/fbf10080bb369cfef1f230c2cd5135a558b242d5/Lib/argparse.py#L1407-L1410) when `argument_default=` is supplied, but our `_FlagAction` and `_BooleanFlagAction` don't support it. Since absl.flags use dest=argparse.SUPPRESS and the default value is never seen through the argparse namespace, we can simply add a `default=` argument and ignore it.

**Comment by MalcolmSlaney** [comment]
Is there a workaround?

**Comment by yilei** [comment]
There isn't a good workaround before we put out a fix, but you could monkey patch these methods to have an extra `default=` argument:

https://github.com/abseil/abseil-py/blob/4d8ea27b446c943a10a3e9ec60c9a7a2980508ba/absl/flags/argparse_flags.py#L240
https://github.com/abseil/abseil-py/blob/4d8ea27b446c943a10a3e9ec60c9a7a2980508ba/absl/flags/argparse_flags.py#L267
