### ISSUE TITLE
Initializing root logger

### ISSUE THREAD

**Issue by adamgayoso** [abseil/abseil-py#188]
I feel that the root logger should not be set by a single python package. This is creating double logging for our [package](https://github.com/scverse/scvi-tools) that depends on Flax, Jax, etc, as we have our own handler on the logger in our namespace.

https://github.com/abseil/abseil-py/blob/3e4749af698201224165a98930c6845d8c102e0d/absl/logging/__init__.py#L559-L560

I could be wrong but in this code:

https://github.com/abseil/abseil-py/blob/3e4749af698201224165a98930c6845d8c102e0d/absl/logging/__init__.py#L1246-L1252

The handler should be added with `_absl_logger.addHandler(_absl_handler)` while `logging.setLoggerClass(ABSLLogger)` should be `_absl_logger.setLoggerClass(ABSLLogger)` with the surrounding lines removed

**Comment by yilei** [comment]
(1) Re the first reference of calling `logging.basicConfig()`: this is the same behavior in Python's own std logging library:

https://github.com/python/cpython/blob/8f31bf46980956c735dd18f9914f3e7144e87c77/Lib/logging/__init__.py#L2140-L2141

(2) Re the second reference, the `_absl_handler` is created at `absl.logging` _import time_ but not added to any logger, to avoid exactly the double logging issue. The handler is only added to the root logger when `use_absl_handler()` is explicitly called, e.g. if you use `absl.app.run()` (see https://github.com/abseil/abseil-py/blob/3e4749af698201224165a98930c6845d8c102e0d/absl/app.py#L372)

So if you are seeing double logging:

1. because of the `logging.basicConfig()` call from (1), then it's the same behavior if use you std logging statements.
2. because of half of the logs are from the _absl_handler, then somewhere `use_absl_handler()` is called (or much less likely that you explicitly added _absl_handler to a logger).

**Comment by adamgayoso** [comment]
Thank you, our problem was actually found elsewhere! Thanks for the info!
