### ISSUE TITLE
Create git-tags in this repositories for the different versions.

### ISSUE THREAD

**Issue by mishas** [abseil/abseil-py#32]
Would it be possible to create Git Tags in the repository that correspond to the version in `setup.py`?

That would help other projects that use Bazel to depend on the project in a more explicit way (using the `tag:` attribute of git_project rather than the `commit:` one.

**Comment by yilei** [comment]
Right now, we are intentionally not providing such tags, since we want users to "Live at Head", and de-emphasize the version. We have to put a version in setup.py since we need to release it on PyPI. And we try to keep a weekly version update.

That being said, manually picking (and updating) the `commit:` hash isn't ideal. We are working on something that will be integrated with bazel to improve this area, stay tuned.

**Comment by yilei** [comment]
Update: we are providing git-tags that map to PyPI releases.
