### ISSUE TITLE
Namespaced Flags?

### ISSUE THREAD

**Issue by wkiser** [abseil/abseil-py#43]
Are all flag names assumed to be globally unique within an Abseil application? For example, assume I have a main application with a `debug` flag, that imports a library that also supplies a `debug` flag that is unrelated to the one in the main application. It would be awesome if I could provide: `__main__.debug=false webapp.lib.debug=true`as my command line and have both flags parsed correctly.

Do you think this is a worthwhile use case to support? It would be great for large applications where your libraries and applications are developed independently, and probably by different teams.

I could force namespaced flags by requiring each name to be defined as `__name__ + '.' + name`, but  it would be awesome if the library supported it out of the box.

Happy to help with a PR if needed.

**Comment by yilei** [comment]
Hi Warren,

Yes they should be globally unique within an application. They are essentially global variables, and they can be changed anywhere in the program. I think namespaces are outside the scope of `absl.flags`.

Also, we usually don't use `.` in flag names, as flags are accessed via `FLAGS.name`.

For libraries authors, we suggest avoiding flags if possible. Use things like extra parameters to functions / class constructors so that:
1. it avoids introducing a global variable;
2. the end client can choose to either 1) not expose a flag at all; 2) choose whatever name they like.

If one must, try using a more unique name than `debug`.

Hope this helps.
