### ISSUE TITLE
Boolean Flags shows inconsistent behavior

### ISSUE THREAD

**Issue by gokul-uf** [abseil/abseil-py#84]
This is in reference to https://github.com/tensorflow/tensorflow/issues/379

`--boolean_flag False` evaluates to `True` while `--boolean_flag=False` works as expected.

**Comment by Zhiqiang-Ye** [comment]
I had the same issue with absl=0.3.0. Default False became True.

**Comment by jhagege** [comment]
Any solution for this ? Thanks

**Comment by dthkao** [comment]
Regarding the first comment, this is because --boolean_flag False is parsed as:

 [--[no]boolean_flag](https://github.com/abseil/abseil-py/blob/9d73fdaa23a6b6726aa5731390f388c0c6250ee5/absl/flags/_defines.py#L249-L255) [\<non-argument\>](https://github.com/abseil/abseil-py/blob/9d73fdaa23a6b6726aa5731390f388c0c6250ee5/absl/flags/_flagvalues.py#L700)

The `--boolean_flag=(true|false)` is actually the undocumented behavior in this case.

**Comment by yilei** [comment]
@dthkao is correct.

See https://abseil.io/docs/python/guides/flags:

`DEFINE_bool` or `DEFINE_boolean`: typically does not take an argument: pass `--myflag` to set `FLAGS.myflag` to `True`, or `--nomyflag` to set `FLAGS.myflag` to `False`.

And specifically:

`--myflag=true` and `--myflag=false` are also supported, but *not recommended*.

Feel free to re-open if you have more questions.
