### ISSUE TITLE
Minor: Website says "2017"

### ISSUE THREAD

**Issue by AXGKl** [abseil/abseil-py#89]
Hi just discovered this beauty and want to market it within the company. 

=> would be good if you could update https://abseil.io - on the bottom it makes this unjustified outdated impression, saying 

![image](https://user-images.githubusercontent.com/9989548/50976264-d6809100-14ef-11e9-82ad-1d9562b60861.png)

**Comment by dthkao** [comment]
For reference, here's a few explanations on how copyright notices work: https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

Also, if anything this probably should be an issue filed in the webpage repository: https://github.com/abseil/abseil.github.io/issues

**Comment by gpshead** [comment]
indeed, the copyright notice should never be seen as a "last updated on" date.  as a company we intentionally avoid updating them as it would lead to needless churn all over.  regardless, your desire for an indication of how active the project is in the documentation makes sense.  file that in the tracker @dthkao mentioned.  otherwise i recommend pointing at the github repository changelog for the code as the source of truth for that, as that shows how often something has been updated.
